package com.fos9we.fm.bean;

public class Category {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_category.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_category.name
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_category.parent_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_category.id
     *
     * @return the value of fm_category.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_category.id
     *
     * @param id the value for fm_category.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_category.name
     *
     * @return the value of fm_category.name
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_category.name
     *
     * @param name the value for fm_category.name
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_category.parent_id
     *
     * @return the value of fm_category.parent_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_category.parent_id
     *
     * @param parentId the value for fm_category.parent_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}