package com.fos9we.fm.bean;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_order.id
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_order.state
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_order.date
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    private Long date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_order.product_id
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    private Long productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_order.user_id
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_order.name
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_order.phone
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_order.address
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_order.id
     *
     * @return the value of fm_order.id
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_order.id
     *
     * @param id the value for fm_order.id
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_order.state
     *
     * @return the value of fm_order.state
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_order.state
     *
     * @param state the value for fm_order.state
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_order.date
     *
     * @return the value of fm_order.date
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public Long getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_order.date
     *
     * @param date the value for fm_order.date
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public void setDate(Long date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_order.product_id
     *
     * @return the value of fm_order.product_id
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public Long getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_order.product_id
     *
     * @param productId the value for fm_order.product_id
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public void setProductId(Long productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_order.user_id
     *
     * @return the value of fm_order.user_id
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_order.user_id
     *
     * @param userId the value for fm_order.user_id
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_order.name
     *
     * @return the value of fm_order.name
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_order.name
     *
     * @param name the value for fm_order.name
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_order.phone
     *
     * @return the value of fm_order.phone
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_order.phone
     *
     * @param phone the value for fm_order.phone
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_order.address
     *
     * @return the value of fm_order.address
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_order.address
     *
     * @param address the value for fm_order.address
     *
     * @mbg.generated Sat May 16 18:58:19 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}