package com.fos9we.fm.bean;

public class Privilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_privilege.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_privilege.name
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_privilege.description
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_privilege.type
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_privilege.parent_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long parentId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_privilege.id
     *
     * @return the value of fm_privilege.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_privilege.id
     *
     * @param id the value for fm_privilege.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_privilege.name
     *
     * @return the value of fm_privilege.name
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_privilege.name
     *
     * @param name the value for fm_privilege.name
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_privilege.description
     *
     * @return the value of fm_privilege.description
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_privilege.description
     *
     * @param description the value for fm_privilege.description
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_privilege.type
     *
     * @return the value of fm_privilege.type
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_privilege.type
     *
     * @param type the value for fm_privilege.type
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_privilege.parent_id
     *
     * @return the value of fm_privilege.parent_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_privilege.parent_id
     *
     * @param parentId the value for fm_privilege.parent_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }
}