package com.fos9we.fm.bean;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_product.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_product.title
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_product.price
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_product.media
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private String media;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_product.state
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_product.category_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long categoryId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_product.user_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_product.description
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_product.id
     *
     * @return the value of fm_product.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_product.id
     *
     * @param id the value for fm_product.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_product.title
     *
     * @return the value of fm_product.title
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_product.title
     *
     * @param title the value for fm_product.title
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_product.price
     *
     * @return the value of fm_product.price
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_product.price
     *
     * @param price the value for fm_product.price
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setPrice(Long price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_product.media
     *
     * @return the value of fm_product.media
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public String getMedia() {
        return media;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_product.media
     *
     * @param media the value for fm_product.media
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setMedia(String media) {
        this.media = media == null ? null : media.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_product.state
     *
     * @return the value of fm_product.state
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_product.state
     *
     * @param state the value for fm_product.state
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_product.category_id
     *
     * @return the value of fm_product.category_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_product.category_id
     *
     * @param categoryId the value for fm_product.category_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_product.user_id
     *
     * @return the value of fm_product.user_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_product.user_id
     *
     * @param userId the value for fm_product.user_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_product.description
     *
     * @return the value of fm_product.description
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_product.description
     *
     * @param description the value for fm_product.description
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }
}