package com.fos9we.fm.bean;

public class RolePrivilege {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_role_privilege.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_role_privilege.role_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_role_privilege.privilege_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    private Long privilegeId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_role_privilege.id
     *
     * @return the value of fm_role_privilege.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_role_privilege.id
     *
     * @param id the value for fm_role_privilege.id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_role_privilege.role_id
     *
     * @return the value of fm_role_privilege.role_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_role_privilege.role_id
     *
     * @param roleId the value for fm_role_privilege.role_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_role_privilege.privilege_id
     *
     * @return the value of fm_role_privilege.privilege_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public Long getPrivilegeId() {
        return privilegeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_role_privilege.privilege_id
     *
     * @param privilegeId the value for fm_role_privilege.privilege_id
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    public void setPrivilegeId(Long privilegeId) {
        this.privilegeId = privilegeId;
    }
}