package com.fos9we.fm.bean;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.id
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.name
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.phone
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.address
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.password
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.gender
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.birth
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private Long birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.postcode
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.register_time
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private Long registerTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fm_user.userFace
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    private String userface;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.id
     *
     * @return the value of fm_user.id
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.id
     *
     * @param id the value for fm_user.id
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.name
     *
     * @return the value of fm_user.name
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.name
     *
     * @param name the value for fm_user.name
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.phone
     *
     * @return the value of fm_user.phone
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.phone
     *
     * @param phone the value for fm_user.phone
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.address
     *
     * @return the value of fm_user.address
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.address
     *
     * @param address the value for fm_user.address
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.password
     *
     * @return the value of fm_user.password
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.password
     *
     * @param password the value for fm_user.password
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.gender
     *
     * @return the value of fm_user.gender
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.gender
     *
     * @param gender the value for fm_user.gender
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.birth
     *
     * @return the value of fm_user.birth
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public Long getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.birth
     *
     * @param birth the value for fm_user.birth
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setBirth(Long birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.postcode
     *
     * @return the value of fm_user.postcode
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.postcode
     *
     * @param postcode the value for fm_user.postcode
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.register_time
     *
     * @return the value of fm_user.register_time
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public Long getRegisterTime() {
        return registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.register_time
     *
     * @param registerTime the value for fm_user.register_time
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setRegisterTime(Long registerTime) {
        this.registerTime = registerTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fm_user.userFace
     *
     * @return the value of fm_user.userFace
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public String getUserface() {
        return userface;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fm_user.userFace
     *
     * @param userface the value for fm_user.userFace
     *
     * @mbg.generated Wed Apr 29 14:39:36 CST 2020
     */
    public void setUserface(String userface) {
        this.userface = userface == null ? null : userface.trim();
    }
}