package com.fos9we.fm.dao;

import com.fos9we.fm.bean.Privilege;
import com.fos9we.fm.bean.PrivilegeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    long countByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int deleteByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int insert(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int insertSelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    List<Privilege> selectByExample(PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    Privilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int updateByExample(@Param("record") Privilege record, @Param("example") PrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int updateByPrimaryKeySelective(Privilege record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_privilege
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int updateByPrimaryKey(Privilege record);
}