package com.fos9we.fm.dao;

import com.fos9we.fm.bean.UserRole;
import com.fos9we.fm.bean.UserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    long countByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int deleteByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int insert(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int insertSelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    List<UserRole> selectByExample(UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    UserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int updateByExample(@Param("record") UserRole record, @Param("example") UserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int updateByPrimaryKeySelective(UserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fm_user_role
     *
     * @mbg.generated Fri Apr 03 21:03:31 CST 2020
     */
    int updateByPrimaryKey(UserRole record);
}